CREATE TABLE events
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT NULL,
  location VARCHAR(100) NOT NULL,
  host VARCHAR(100) NOT NULL,
  status VARCHAR(100) NOT NULL
);